# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e95aeb94d3693728c99a07cf63cfe74f"
name = "CartWhisperAI"
application_url = "https://cartwhisperai-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# read_customers is required to access customer data in orders
scopes = "write_products,read_products,read_orders,read_customers"

[auth]
redirect_urls = [ "https://cartwhisperai-production.up.railway.app/auth/callback" ]

[app_proxy]
url = "https://cartwhisperai-production.up.railway.app/api/proxy"
subpath = "chat-proxy"
prefix = "apps"
